channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.12
  - conda-forge::pip
  - conda-forge::setuptools
  - conda-forge::ipython
  - conda-forge::ipykernel
  - pip:
      - "pyyaml"
      - -e cybercomp-python-sdk/
