description: "prepare executable code for a neuro network"

parameters:
  template: {type: "path"}
  overrides: {type: "path"}
  out_dir: {type: "path", default: "out"}
  MAX_SUBNET_POINTS: {type: "numeric", default: 12500}
  s2_scale: {type: "numeric", default: 1.2}
  s3_scale: {type: "numeric", default: 1.8}
  rem_scale: {type: "numeric", default: 0.9}
  gkl_awake: {type: "numeric", default: 0.19}
  gkl_awake_fix: {type: "numeric", default: 0.19}
  gkl_TC_awake: {type: "numeric", default: 0.79}
  gkl_TC_awake_fix: {type: "numeric", default: 0.79}
  gkl_RE_awake: {type: "numeric", default: 0.9}
  gkl_RE_awake_fix: {type: "numeric", default: 0.9}
  awake_AMPAd2: {type: "numeric", default: 0.2}
  awake_AMPAd2_fix: {type: "numeric", default: 0.2}
  gh_TC_awake: {type: "numeric", default: -8.0}
  gh_TC_s2: {type: "numeric", default: -3.0}
  gh_TC_s3: {type: "numeric", default: -2.0}
  gh_TC_rem: {type: "numeric", default: 0.0}
  awake_GABAd2: {type: "numeric", default: 0.22}
  awake_GABAd2_fix: {type: "numeric", default: 0.22}
  awake_GABA_TC: {type: "numeric", default: 0.55}
  awake_GABA_TC_fix: {type: "numeric", default: 0.55}
  awake_AMPA_TC: {type: "numeric", default: 0.5}
  s2_AMPA_TC: {type: "numeric", default: 0.5}
  s3_AMPA_TC: {type: "numeric", default: 0.5}
  rem_AMPA_TC: {type: "numeric", default: 0.5}
  gk_cx_slow_awake: {type: "numeric", default: 1.0}
  gk_cx_slow_s2: {type: "numeric", default: 1.0}
  gk_cx_slow_s3: {type: "numeric", default: 1.0}
  gk_cx_slow_rem: {type: "numeric", default: 1.0}
  gk_cx_spike_awake: {type: "numeric", default: 1.0}
  gk_cx_spike_s2: {type: "numeric", default: 1.0}
  gk_cx_spike_s3: {type: "numeric", default: 1.0}
  I_HH: {type: "numeric", default: 1}
  N_RE: {type: "numeric", default: 7}
  N_TC: {type: "numeric", default: 12}
  N_GB: {type: "numeric", default: 2}
  N_TCa: {type: "numeric", default: 12}
  N_DEND_1: {type: "numeric", default: 9}
  N_SOMA: {type: "numeric", default: 4}
  TAU: {type: "numeric", default: 0.02}
  TAU_Map: {type: "numeric", default: 0.5}
  TAUr: {type: "numeric", default: 25}
  RE_E_l: {type: "numeric", default: -77}
  RE_G_Ca: {type: "numeric", default: 2.2}
  RE_G_kl: {type: "numeric", default: 0.012}
  GABA_A_E_GABA: {type: "numeric", default: -70}
  TCcore_G_A: {type: "numeric", default: 0}
  TCcore_ginc: {type: "numeric", default: 2.0}
  TCcore_E_l: {type: "numeric", default: -70}
  TCcore_G_Ca: {type: "numeric", default: 2.5}
  TCcore_D: {type: "numeric", default: 2}
  TCcore_pc: {type: "numeric", default: 0.007}
  TCcore_k4: {type: "numeric", default: 0.001}
  TCcore_Vtr: {type: "numeric", default: -40}
  TCcore_VtrK: {type: "numeric", default: -28}
  TCcore_G_K: {type: "numeric", default: 12}
  TCcore_G_h: {type: "numeric", default: 0.016}
  TCcore_G_kl: {type: "numeric", default: 0.024}
  TCcore_DC: {type: "numeric", default: 0}
  TCcore_memory_E_GABA: {type: "numeric", default: -83}
  TCcore_memory_GB_K1: {type: "numeric", default: 0.5}
  TCcore_memory_GB_K2: {type: "numeric", default: 0.0012}
  TCcore_memory_GB_K3: {type: "numeric", default: 0.1}
  TCcore_memory_GB_K4: {type: "numeric", default: 0.034}
  TCmatrix_G_A: {type: "numeric", default: 0}
  TCmatrix_ginc: {type: "numeric", default: 2}
  TCmatrix_E_l: {type: "numeric", default: -70}
  TCmatrix_G_Ca: {type: "numeric", default: 2.2}
  TCmatrix_D: {type: "numeric", default: 2}
  TCmatrix_pc: {type: "numeric", default: 0.007}
  TCmatrix_k4: {type: "numeric", default: 0.001}
  TCmatrix_Vtr: {type: "numeric", default: -40}
  TCmatrix_VtrK: {type: "numeric", default: -28}
  TCmatrix_G_K: {type: "numeric", default: 12}
  TCmatrix_G_h: {type: "numeric", default: 0.015}
  TCmatrix_G_kl: {type: "numeric", default: 0.025}
  TCmatrix_DC: {type: "numeric", default: 0}
  TCmatrix_memory_E_GABA: {type: "numeric", default: -83}
  TCmatrix_memory_GB_K1: {type: "numeric", default: 0.5}
  TCmatrix_memory_GB_K2: {type: "numeric", default: 0.0012}
  TCmatrix_memory_GB_K3: {type: "numeric", default: 0.1}
  TCmatrix_memory_GB_K4: {type: "numeric", default: 0.034}
  CXsyn_G_kl: {type: "numeric", default: 0.011}
  CXsyn_E_l: {type: "numeric", default: -67.0}
  CXsyn_G_Km: {type: "numeric", default: 0.02}
  CXsyn_G_l: {type: "numeric", default: 0.011}
  CXasyn_G_kl: {type: "numeric", default: 0.01}
  CXasyn_E_l: {type: "numeric", default: -68}
  CXasyn_G_Km: {type: "numeric", default: 0.02}
  CXasyn_G_l: {type: "numeric", default: 0.022}
  CXsyn6_G_kl: {type: "numeric", default: 0.01}
  CXsyn6_E_l: {type: "numeric", default: -68}
  CXsyn6_G_Km: {type: "numeric", default: 0.02}
  CXsyn6_G_l: {type: "numeric", default: 0.022}
  INsynCore_rho: {type: "numeric", default: 50}
  INsynCore_DEND_G_Nap: {type: "numeric", default: 0.0}
  INsynCore_SOMA_G_Nap: {type: "numeric", default: 0.0}
  INsynCore_SOMA_G_Na: {type: "numeric", default: 2500}
  INsynCore_E_l: {type: "numeric", default: -75}
  INsynCore_G_Km: {type: "numeric", default: 0.02}
  INsynCore_G_Kl: {type: "numeric", default: 0.009}
  INsynCore_G_l: {type: "numeric", default: 0.009}
  INsynMatrix_rho: {type: "numeric", default: 50}
  INsynMatrix_DEND_G_Nap: {type: "numeric", default: 0.0}
  INsynMatrix_SOMA_G_Nap: {type: "numeric", default: 0.0}
  INsynMatrix_SOMA_G_Na: {type: "numeric", default: 2500}
  INsyn6_rho: {type: "numeric", default: 50}
  INsyn6_DEND_G_Nap: {type: "numeric", default: 0.0}
  INsyn6_SOMA_G_Nap: {type: "numeric", default: 0.0}
  INsyn6_SOMA_G_Na: {type: "numeric", default: 2500}
  RS_HHH: {type: "numeric", default: 0.02}
  RS_mu: {type: "numeric", default: 0.0005}
  RS_spike: {type: "numeric", default: 0}
  RS_alpha: {type: "numeric", default: 3.65}
  RS_sigma: {type: "numeric", default: 0.02}
  RS_sigma_e: {type: "numeric", default: 1.0}
  RS_sigma_dc: {type: "numeric", default: 1.0}
  RS_beta_e: {type: "numeric", default: 0.133}
  RS_beta_dc: {type: "numeric", default: 0.133}
  RS_Idc: {type: "numeric", default: 0}
  RS_S_CX_DEND: {type: "numeric", default: 165.0e-6}
  RS_Tcr: {type: "numeric", default: -100}
  RS_v_DEND: {type: "numeric", default: -60}
  RS_v_SOMA: {type: "numeric", default: -60}
  FS1_ii: {type: "numeric", default: 0}
  FS1_mu: {type: "numeric", default: 0.002}
  FS1_spike: {type: "numeric", default: 0}
  FS1_alpha: {type: "numeric", default: 3.8}
  FS1_sigma: {type: "numeric", default: -1.75E-2}
  FS1_sigma_e: {type: "numeric", default: 0.5}
  FS1_sigma_dc: {type: "numeric", default: 1.0}
  FS1_beta_e: {type: "numeric", default: 0.05}
  FS1_beta_dc: {type: "numeric", default: 0.1}
  FS1_Idc: {type: "numeric", default: -0.}
  FS1_S_CX_DEND: {type: "numeric", default: 165.0e-6}
  FS1_gg: {type: "numeric", default: 0.5}
  FS1_beta_ii: {type: "numeric", default: 0.5}
  FS1_sigma_ii: {type: "numeric", default: 0.5}
  FS1_Tcr: {type: "numeric", default: -100}
  FS1_v_DEND: {type: "numeric", default: -60}
  FS1_v_SOMA: {type: "numeric", default: -60}
  IT_RE_G_Ca: {type: "numeric", default: 1.75}
  IT_RE_Qm: {type: "numeric", default: 5}
  IT_RE_Qh: {type: "numeric", default: 3}
  INaK_G_K: {type: "numeric", default: 10}
  INaK_G_Na: {type: "numeric", default: 100}
  INaK_Vtr: {type: "numeric", default: -50}
  INaK_VtrK: {type: "numeric", default: -50}
  Ih_TC_G_h: {type: "numeric", default: 0.02}
  Ih_TC_ginc: {type: "numeric", default: 1.5}
  Ih_TC_cac: {type: "numeric", default: 0.0015}
  Ih_TC_pc: {type: "numeric", default: 0.01}
  Ih_TC_k3: {type: "numeric", default: 0.001}
  IA_TC_G_A: {type: "numeric", default: 1}
  IHVA_CX_G_HVA: {type: "numeric", default: 0.03}
  IKCa_CX_G_KCa: {type: "numeric", default: 0.3}
  IKm_CX_G_Km: {type: "numeric", default: 0.01}
  IKv_CX_G_Kv: {type: "numeric", default: 150}
  INa_CX_G_Na: {type: "numeric", default: 3000}
  INap_CX_G_Nap: {type: "numeric", default: 2}
  INap_CX_Tet: {type: "numeric", default: -42}
  INap_CX_Sig: {type: "numeric", default: 5}
  INap_CX_f: {type: "numeric", default: 0.02}
  INap_CX_Cels: {type: "numeric", default: 36}
  INap_CX_Q10: {type: "numeric", default: 2.7}
  GABA_A_old_v: {type: "numeric", default: 0}
  GABA_A_E_GABA: {type: "numeric", default: -70}
  GABA_A_R: {type: "numeric", default: 0}
  GABA_A_C: {type: "numeric", default: 0}
  GABA_A_R0: {type: "numeric", default: 0}
  GABA_A_R1: {type: "numeric", default: 0}
  GABA_A_Alpha: {type: "numeric", default: 10.5}
  GABA_A_Beta: {type: "numeric", default: 0.166}
  GABA_A_lastrelease: {type: "numeric", default: -100}
  GABA_B_old_v: {type: "numeric", default: 0}
  GABA_B_Cdur: {type: "numeric", default: 0.3}
  GABA_B_K1: {type: "numeric", default: 0.52}
  GABA_B_K2: {type: "numeric", default: 0.0013}
  GABA_B_K3: {type: "numeric", default: 0.098}
  GABA_B_K4: {type: "numeric", default: 0.033}
  GABA_B_lastrelease: {type: "numeric", default: -10000000}
  GABA_B_C: {type: "numeric", default: 0}
  GABA_B_r0: {type: "numeric", default: 0}
  GABA_B_g0: {type: "numeric", default: 0}
  GB_lastrelease: {type: "numeric", default: -10000000}
  GB_C: {type: "numeric", default: 0}
  network_config: {type: "env", default: "$(network_config)"}
  network_mri: {type: "env", default: "$(network_mri)"}
  subnet_3d: {type: "env", default: "$(subnet_3d)"}
  distance_3d: {type: "env", default: "$(distance_3d)"}
  connection_info: {type: "env", default: "$(connection_info)"}
  stim_config: {type: "env", default: "$(stim_config)"}

observables:
  code: {type: "path"}

run:
  engine:
    - bash
    - python
  command: "
    python -m sub
    -s {{parameters.template}}
    -p {{parameters.overrides}}
    -t {{observables.code}}
    "
