description: "train a ML model"
required_parameters:
  dl_model: "file"
  dl_dataset: "file"
  dl_epochs: "file"
  dl_optimizer: "file"
  dl_scheduler: "file"
optional_parameters:
  dl_model_weights: "file"
observables:
  dl_model: "file"
